# Gettting Started

## What can be forecast?

Whether we can or cannot forecast an event depends on a few factors,

1. how well we understand the contributing factors of the forecast;
2. how much data is available;
3. how similar the future is to the past;
4. whether the forecast can affect the thing we trying to forecast;

For example, residential electricity demand can be forecast with high accuracy for short term since it satisfies all the four conditions, while predicting the exchange rate is difficult, since it statisfies only the condition (2), specifically violates the condition (4).


## Questions to consider when forecasting

1. About what forecasts should be made?
2. What would be the forecasting horizon?
3. How frequently are forecasts required?

> The further ahead we forecase, the more uncertain we are!

## Forecasting Data & Methods

- **Qualitative forecasting**: When historical data are not available. Or the available data are not relevant to the forecasts.

- **Quantitative forecasting**: When historical data are available and we can assume some aspect of past patterns will continue to prevail in the future too.


